 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/divisions", type: :request do
  
  # Division. As you add validations to Division, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Division.create! valid_attributes
      get divisions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      division = Division.create! valid_attributes
      get division_url(division)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_division_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      division = Division.create! valid_attributes
      get edit_division_url(division)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Division" do
        expect {
          post divisions_url, params: { division: valid_attributes }
        }.to change(Division, :count).by(1)
      end

      it "redirects to the created division" do
        post divisions_url, params: { division: valid_attributes }
        expect(response).to redirect_to(division_url(Division.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Division" do
        expect {
          post divisions_url, params: { division: invalid_attributes }
        }.to change(Division, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post divisions_url, params: { division: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested division" do
        division = Division.create! valid_attributes
        patch division_url(division), params: { division: new_attributes }
        division.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the division" do
        division = Division.create! valid_attributes
        patch division_url(division), params: { division: new_attributes }
        division.reload
        expect(response).to redirect_to(division_url(division))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        division = Division.create! valid_attributes
        patch division_url(division), params: { division: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested division" do
      division = Division.create! valid_attributes
      expect {
        delete division_url(division)
      }.to change(Division, :count).by(-1)
    end

    it "redirects to the divisions list" do
      division = Division.create! valid_attributes
      delete division_url(division)
      expect(response).to redirect_to(divisions_url)
    end
  end
end
