default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: self_introduction_app_development
  username: postgres
  password: QB7StzzZE78i

test:
  <<: *default
  database: self_introduction_app_test
  username: postgres
  password: QB7StzzZE78i

production:
  <<: *default
  database: self_introduction_app_production
  username: self_introduction_app
  password: <%= ENV['SELF_INTRODUCTION_APP_DATABASE_PASSWORD'] %>
