default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: self_introduction_app_development
  username: postgres
  password: QB7StzzZE78i

test:
  <<: *default
  database: self_introduction_app_test
  username: postgres
  password: QB7StzzZE78i

production:
  <<: *default
  database: <%= ENV['RAILS_DATABASE_NAME'] || Rails.application.credentials.db[:database] %>
  username: <%= ENV['RAILS_DATABASE_USERNAME'] || Rails.application.credentials.db[:username] %>
  password: <%= ENV['RAILS_DATABASE_USERPASSWORD'] || Rails.application.credentials.db[:userpass] %>
  host:  <%= ENV['RAILS_DATABASE_HOST'] || Rails.application.credentials.db[:host] %>
