default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: self_introduction_app_development
  username: postgres
  password: QB7StzzZE78i

test:
  <<: *default
  database: self_introduction_app_test
  username: postgres
  password: QB7StzzZE78i

production:
  <<: *default
  database: <%= Rails.application.credentials.db[:database] %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:userpass] %>
  host:  <%= Rails.application.credentials.db[:host] %>
